version: '3.8'

services:
  errorhandling:
    image: errorhandling
    build:
      context: .
      dockerfile: ErrorhandlingService/Dockerfile

  # mongodb:
  #   image: ${DOCKER_REGISTRY-}/mongo:latest
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - ./mongo/data/:/data/db/
  
  # prometheus:
  #   image: prom/prometheus:v2.30.0
  #   volumes:
  #     - ./config:/etc/prometheus
  #     - ./data:/prometheus
  #   ports:
  #     - 9090:9090
  
  # alertmanager:  
  #   image: prom/alertmanager
  #   container_name: alertmanager
  #   hostname: alertmanager
  #   restart: always
  #   ports:
  #       - "9093:9093"
  #   networks:
  #       - monitor

  # grafana:
  #   image: grafana/grafana
  #   container_name: grafana
  #   hostname: grafana
  #   restart: always
  #   ports:
  #       - "3000:3000"
  #   networks:
  #       - monitor

  # node-exporter:  #主機數據
  #   image: quay.io/prometheus/node-exporter
  #   container_name: node-exporter
  #   hostname: node-exporter
  #   restart: always
  #   ports:
  #       - "9100:9100"
  #   networks:
  #       - monitor

  # cadvisor:  #容器數據
  #   image: google/cadvisor:latest
  #   container_name: cadvisor
  #   hostname: cadvisor
  #   restart: always
  #   volumes:
  #       - /:/rootfs:ro
  #       - /var/run:/var/run:rw
  #       - /sys:/sys:ro
  #       - /var/lib/docker/:/var/lib/docker:ro
  #   ports:
  #       - "8899:8080"
  #   networks:
  #       - monitor

  
# networks:
#     monitor:
#         driver: bridge

  