scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
      
  - job_name: 'cadvisor'
    static_configs:
    - targets: ['host.docker.internal:8899']

  - job_name: 'node'
    static_configs:
    - targets: ['host.docker.internal:9100']

