@startuml

!include DatabaseCollectionHandler.puml
!include ErrorHandlingService.puml
!include Model.puml
!include BackgroundService.puml

DatatbaseHandler..|>IDatabaseHandler
WarningReport..|>IWarningReport


IDatabaseHandler <-- WarningReport
IDatabaseHandler <-- PrometheusService
PrometheusService <-- GrafanaService

WarningReport - DataModel

@enduml