package ErrorHandlingService{
    class ErrorService{
        + PostWarningReportRequest
        + GetWarningReportRequest
    }

    class PrometheusService{}

    class GrafanaService{}
    Interface IErrorService{}
}