package WarningReportService{
    class WarningReport{
        + PostWarningReportRequest
        + GetWarningReportRequest
    }

    class PrometheusService{}

    class GrafanaService{}
    Interface IWarningReport{}
}